# Generated by Django 4.2.1 on 2023-05-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('equipo_local', models.CharField(max_length=50)),
                ('equipo_visitante', models.CharField(max_length=50)),
                ('goles_local', models.CharField(max_length=50)),
                ('goles_visitante', models.CharField(max_length=50)),
                ('ganador', models.CharField(max_length=50)),
            ],
        ),
    ]
